# ⚙️ Reto 2 – Filtros y condiciones en Pandas

**Objetivo:** aplicar filtros y condiciones lógicas para clasificar los datos.

In [2]:
import pandas as pd
datos = pd.read_csv('../data/4_resultados_agua.csv')

### 🔹 Ejemplo de comparación
Puedes filtrar las filas según una condición, por ejemplo pH mayor a 8.5:

In [3]:
datos[datos['pH'] > 7.1]

  Punto   Temp    pH  OD_promedio
0     A  22.25  7.15          6.2
1     B  24.30  7.20          5.8
4     E  25.15  7.25          5.0

### 💡 Actividad
- Crea al menos dos condiciones (por pH y temperatura).
- Genera una nueva columna con la categoría resultante.

In [4]:
# Condición 1: puntos con pH menor a 7
datos[datos["pH"] < 7]

  Punto  Temp    pH  OD_promedio
2     C  19.8  6.85          4.9

In [5]:
# Condición 2: puntos con temperatura mayor o igual a 24
datos[datos["Temp"] >= 24]

  Punto   Temp    pH  OD_promedio
1     B  24.30  7.20          5.8
4     E  25.15  7.25          5.0

In [9]:
datos["estado_pH"] = "aceptable"
datos.loc[datos["pH"] < 7, "estado_pH"] = "bajo"

In [10]:
datos["categoria"] = "pH aceptable y temperatura alta"

datos.loc[(datos["pH"] < 7) & (datos["Temp"] < 22), "categoria"] = "pH bajo y temperatura baja"

datos.loc[(datos["pH"] < 7) & (datos["Temp"] >= 22), "categoria"] = "pH bajo y temperatura alta"

datos.loc[(datos["pH"] >= 7) & (datos["Temp"] < 24), "categoria"] = "pH aceptable y temperatura moderada"

In [8]:
datos["categoria"].value_counts()

categoria
pH aceptable y temperatura moderada    2
pH aceptable y temperatura alta        2
pH bajo y temperatura baja             1
Name: count, dtype: int64

## Conclusión

En este notebook se aplicaron filtros sobre las variables `pH` y `Temp` para seleccionar registros específicos del dataset.  
Además, se creó una nueva columna llamada `Categoria`, que clasifica cada punto según sus valores de pH y temperatura.

Esto permite organizar mejor los datos y facilita su interpretación en análisis posteriores.